#!/bin/bash

if [ "$1" == "remove" ] || [ "$1" == "purge" ]; then

	if [ -d "/usr/local/etc/nzbget" ]; then
		rm -r /usr/local/etc/nzbget &>/dev/null
	fi
	if [ -d "/usr/local/share/nzbget" ]; then
		rm -r /usr/local/share/nzbget &>/dev/null
	fi
fi
