#!/bin/bash

if [ $1 == "install" -o $1 == "upgrade" ]; then

        if [ -d "/usr/local/etc/nzbget/" ]; then

		if [ ! -d "/etc/nzbget" ];then
			mkdir /etc/nzbget
		fi

		mv /usr/local/etc/nzbget/* /usr/local/etc/nzbget/.[^.]* /etc/nzbget/.
		rm -r /usr/local/etc/nzbget
		
	else
		true
	fi

fi
