#!/bin/bash

if [ $1 == "install" -o $1 == "upgrade" ]; then

        if [ -d "/usr/local/etc/nzbget/" ]; then

		mv /usr/local/etc/nzbget /etc/nzbget
		
		ln -s /usr/local/etc/nzbget /etc/nzbget
		
	else
		true
	fi

fi
